apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: test
  labels:
    app: simple-backend
spec:
  selector:
    matchLabels:
      app: simple-backend
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-backend
        tier: backend
    spec:
      containers:
        - image: us.gcr.io/fine-acronym-235020/circleci-gke:v1
          name: test
          ports:
            - containerPort: 3000
              name: test
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  ports:
  - name: http
    targetPort: 3000
    protocol: TCP
    port: 3000
  type: NodePort
  selector:
    app: simple-backend  
    tier: backend         
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: test
spec:
  rules:
  - host: test.cedille.site
    http:
      paths:
      - path: /
        backend:
          serviceName: test
          servicePort: http